cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart_detail, name='cart_detail'),
     path('add/<int:product_id>/',
          views.cart_add,
          name='cart_add'),
     path('remove/<int:product_id>/',
          views.cart_remove,
          name='cart_remove'),
]

myshop/urls.py
from django.urls import path
from . import views
from cart import views as v

app_name = 'myshop'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     path('<slug:category_slug>/', views.product_list,
          name='product_list_by_category'
          ),
     path('<int:id>/<slug:slug>', views.product_detail,
          name='product_detail'),
     path('<int:id>/cart', views.product_detail,
          name='product_detail'),
     path("cart",v.cart_detail, name='cart_detail'), 
     path("orders/cart",v.cart_detail, name='cart_detail'), 
     ]

orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(r'^create/$', views.order_create, name='order_create'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from myshop import views
from cart import views as w

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include(('orders.urls','orders'), namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace='shop')),
    path('aboutus', views.aboutus, name='aboutus'),
    path('contact', views.contact, name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

myshop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                related_name='products',
                                on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('myshop:product_detail', args=[self.id, self.slug])

orders/models.py
from django.db import models
from myshop.models import Product
from phonenumber_field.modelfields import PhoneNumberField

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    phone_number = PhoneNumberField(null = False, blank = False, default = "")

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE,)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE,)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'phone_number', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                {
                    'category': category,
                    'categories': categories,
                    'products': products
                })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})
def aboutus(request):
    return render(
        request,
        'aboutus.html'
    )        

def contact(request):
    return render(
        request,
        'contact.html'
    )            

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                        product=item['product'],
                                        price=item['price'],
                                        quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html',
                        {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                {'cart': cart, 'form': form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  
{% endblock %}

{% block content %}
<style>
  #img {
    height: 100px;
    width: 100px;
}
</style>
  <h1>Корзина покупок</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" id='img'>
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">{{ item.price }}<span> руб.</span></td>
            <td class="num">{{ item.total_price }}<span> руб.</span></td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }}<span> руб.</span></td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">В магазин</a>
    <a href="{% url "orders:order_create" %}" class="button">Оформить заказ</a>
  </p>
{% endblock %}

myshop/templates/aboutus.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <div class="row wow rotateInUpLeft">
        <div class="col-md-6 mb-4">
          <img src="{% static 'img\ivanka.jpg'%}" alt="farm" class="img-fluid">
        </div>
        <div class="col-md-6 mb-4 wow zoomIn">
          <div class="p-4">
            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1"></span>
              </a>
            </div>
            </p>
            <p class="lead font-weight-bold">О нас</p>
            <p>Вам нужен повод для подарка? Нам - нет! У нас каждый новый день праздник! Сотворённого Любовью, лавандового настроения!
              <br>Мы - Ivanka House! Занимаемся мыловарней, а так же продукцией сделанной своими руками. Используем только натуральные продукты
              для создания волшебства!
            </p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>

  {% endblock %}

myshop/templates/contact.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <div class="row wow rotateInUpLeft">
        <p class="lead font-weight-bold">Контакты<br></p>
          <p><br><br>Магазины:
            <a href="https://www.google.com/maps/place/ул.+Раковская+20,+Минск/@53.9051513,27.5477147,18.82z/data=!4m5!3m4!1s0x46dbcfec5ddf6949:0x9dc91fcd890454aa!8m2!3d53.9050445!4d27.5481279">
            г. Минск ул. Раковская 20 "Only you"<br></a>
            <a href="https://www.google.com/maps/place/Цветы+и+подарки+LaRose/@53.9110258,27.4988038,17z/data=!4m13!1m7!3m6!1s0x46dbc545aa5e380f:0xaf6ef0b9e3bb3c57!2z0YPQuy4g0J_RgNC40YLRi9GG0LrQvtCz0L4gMTAsINCc0LjQvdGB0Lo!3b1!8m2!3d53.9110227!4d27.5009978!3m4!1s0x46dbc5f25df1c68f:0x4ce4f9089b78cb72!8m2!3d53.9110227!4d27.5009978">
            г. Минск ул. Притыцкого 10 "La Rose".<br></a>
            Эл. Почта:
            <a href="mail:ivankahouse8@gmail.com">
            ivankahouse8@gmail.com<br></a></p>

        
      </div>
    </div>
  </main>

  {% endblock %}

myshop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  {% block title %}<title>Ivanka House</title>{% endblock %}

  <!-- MDB icon -->
  <link rel="icon" href="{%static 'img/mdb-favicon.ico'%}" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{%static 'css/cart.css'%}">
  <link rel="stylesheet" href="{%static 'css/mdb.min.css'%}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{%static 'css/style.css'%}">
  <link rel="stylesheet" href="{%static 'css/footer.css'%}">
  <style>
    html,
    body,
    header,
    .carousel{
    height: 60vh;
    }

    @media (max-width: 740px){
      html,
      body,
      header,
      .carousel{
      height: 100vh;
    }

    }
    @media (min-width: 740px) and (max-width: 850px) {
      html,
      body,
      header,
      .carousel{
      height: 100vh;
    }
    }
    
  </style>
</head>
<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      <a href="{% url 'shop:product_list' %}" class="navbar-brand waves effect">
        <strong class="purple-text">Ivanka House</strong>
      </a>
      <button class="navbar-toggler" type="button"
      data-toggle="collapse" data-target="#navbarContent"
      aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a href="{% url 'shop:product_list' %}" class="nav-link waves-effect">Главная</a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'aboutus' %}" class="nav-link waves-effect">О нас</a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'contact' %}" class="nav-link waves-effect">Контакты</a>
          </li>
        </ul>
        <form action="../cart" class="d-flex justify-content-left" method="get">
          <input type="submit" class="btn btn-primary btn-md my-0 p color='purple'" value="Корзина">
        </form>
      </div>
    </div> 
  </nav>

  {% block content %}{% endblock %}

  <div class="wrapper">

    <div class="content"></div>
    
      <footer style="margin-top: 16.5rem!important;" class="page-footer footer-light purple text-center font-small wow fadeIn" id="footer1">
        <div class="pt-4">
          <a href="https://www.instagram.com/ivankahouse/" role="button" class="btn btn-outline-white">Ivanka House Instagram</a>
          </a>
        </div>
      </footer>
    
  </div> 
    <!-- jQuery -->
    <script type="text/javascript" src="{%static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{%static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{%static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{%static 'js/mdb.min.js' %}"></script>
    <!-- Your custom scripts (optional) -->
    <script type="text/javascript"></script>

    
</body>
</html>

myshop/templates/shop/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  {% block title %}<title>Ivanka House</title>{% endblock %}
  {% load static %}
  <!-- MDB icon -->
  <link rel="icon" href="{%static 'img/mdb-favicon.ico'%}" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{%static 'css/mdb.min.css'%}">
  <!-- Material Design Bootstrap -->

  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{%static 'css/style.css'%}">
  <style>
    html,
    body,
    header,
    .carousel{
    height: 60vh;
    }

    @media (max-width: 740px){
      html,
      body,
      header,
      .carousel{
      height: 100vh;
    }

    }
    @media (min-width: 740px) and (max-width: 850px) {
      html,
      body,
      header,
      .carousel{
      height: 100vh;
    }
    }
    
  </style>
</head>
<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      <a href="{% url 'shop:product_list' %}" class="navbar-brand waves effect">
        <strong class="purple-text">Ivanka House</strong>
      </a>
      <button class="navbar-toggler" type="button"
      data-toggle="collapse" data-target="#navbarContent"
      aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a href="{% url 'shop:product_list' %}" class="nav-link waves-effect">Главная</a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'aboutus' %}" class="nav-link waves-effect">О нас</a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'contact' %}" class="nav-link waves-effect">Контакты</a>
          </li>
        </ul>
        <form action="cart" class="d-flex justify-content-left" method="post">
          {% csrf_token %}
          <input type="submit" class="btn btn-primary btn-md my-0 p" value="Корзина">
          </button> 
        </form>
      </div>
    </div> 
  </nav>

  {% block content %}{% endblock %}

  <footer class="page-footer footer-light purple fixed-bottom text-center font-small mt-4 wow fadeIn">
    <div class="pt-4">
      <a href="https://www.instagram.com/ivankahouse/" role="button" class="btn btn-outline-white">Ivanka House Instagram</a>
    </div>
    <div class="foooter-copyright py-3">
      Lavanda Farm Ivanka House
    </div>
  </footer>
  <!-- jQuery -->
  <script type="text/javascript" src="{%static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{%static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{%static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{%static 'js/mdb.min.js' %}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>
</body>
</html>

myshop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<style>
  #img {
    height: 500px;
    width: 400px;
}
</style>


<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">
    <div class="row wow rotateInUpLeft">
      <div class="col-md-6 mb-4">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}
        {% static "img/no_image.png" %}{% endif %}" alt="butter" class="img-fluid">
      </div>
      <div class="col-md-6 mb-4 wow zoomIn">
        <div class="p-4">
          <div class="mb-3">
            <a href="{{ product.category.get_absolute_url }}">
              <span class="badge purple mr-1">{{product.category }}</span>
            </a>
          </div>
          <p class="lead">
            <span class="mr-1">
              {{ product.name }}
            </span>
          </p>
          <p class="lead font-weight-bold">Описание</p>
            {{ product.description|linebreaks }}

          <p class="lead">
            <span class="mr-1">
              {{ product.price }}<span> руб</span>.
            </span>
          </p>  

          <form action="{% url 'cart:cart_add' product.id %}" class="d-flex justify-content-left" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-md my-0 p" value="В корзину"/>
            
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block content %}

    <div class="order-info" style="margin-right: 20px;margin-top: 80px;">
        <h3>Ваш заказ</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>{{ item.total_price }}<span> руб.</span></span>
                </li>
            {% endfor %}
        </ul>
        <p>Всего:{{ cart.get_total_price }} <span> руб.</span></p>
    </div>
    <style>
        @media screen and (min-width: 320px) { 
            .form{

                margin-right: 200px;
            }
            
            }    
        @media screen and (min-width: 1920px) { 
            .form{

                margin-left: 650px;
            }
            
            }
        @media screen and (min-width: 1024px) { 
            .form{

                margin-left: 320px;
            }
            
            }
        @media screen and (min-width: 1440px) { 
            .form{

                margin-left: 550px;
            }
            
            } 
            
        @media screen and (min-width: 2560px) { 
            .form{

                margin-left: 1100px;
            }
            
            }  
    
    </style>
    <div class="form">
        <form action="{% url 'orders:order_create' %}" method="post" class="order-form" style="margin: 26px; margin-top: 80px;">
    
            {{ form.as_p }}
            <p><input type="submit" value="Place order"></p>
            {% csrf_token %}
    </form>
    </div>  
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block content %}
<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <div class="row wow rotateInUpLeft">
        <div class="col-md-10 mb-10">
        </div>
        <div class="col-md-6 mb-4 wow zoomIn">
          <div class="p-4">
            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1"></span>
              </a>
            </div>
            </p>
            <p>Спасибо, ваш заказ оформлен, номер заказа <strong>{{ order.id }}</strong>.</p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}